### ISSUE TITLE
Admin Page.

### ISSUE THREAD

**Issue by dov-yih** [dov-yih/speech-registration#5]
+ [x] personal speech list
+ [x] add new speech.
+ [x] change password.
+ [x] edit speech.

**Comment by dov-yih** [comment]
**Optimization**

abstruct the User desconstruction to a helper function.

Or Sequelize had a api for this?

**Comment by yidafu** [comment]
May need common Error Modal components.

**Comment by yidafu** [comment]
Closed! it will fix in next time.
